CREATE DATABASE joyas;
\c joyas;

CREATE TABLE inventario (id SERIAL PRIMARY KEY, nombre VARCHAR(100), categoria VARCHAR(100), metal VARCHAR(100), precio INT, stock INT);

INSERT INTO inventario (nombre, categoria, metal, precio, stock) VALUES ('Silver Necklace', 'Jewelry', 'Silver', 100, 10),
('Gold Ring', 'Jewelry', 'Gold', 250, 5),
('Steel Earrings', 'Jewelry', 'Stainless Steel', 50, 20),
('Leather Watch', 'Accessories', 'Stainless Steel', 120, 8),
('Silver Chain', 'Jewelry', 'Silver', 80, 15),
('Steel Bracelet', 'Jewelry', 'Stainless Steel', 30, 25),
('Sunglasses', 'Accessories', 'Plastic', 50, 12),
('Leather Bag', 'Bags', 'Leather', 200, 3),
('Leather Belt', 'Accessories', 'Leather', 70, 6),
('Wool Scarf', 'Clothing', 'Wool', 40, 30),
('Diamond Ring', 'Jewelry', 'Gold', 500, 2),
('Pearl Earrings', 'Jewelry', 'Silver', 150, 10),
('Silver Bracelet', 'Jewelry', 'Silver', 70, 15),
('Leather Wallet', 'Accessories', 'Leather', 80, 5),
('Gold Necklace', 'Jewelry', 'Gold', 180, 7),
('Silver Ring', 'Jewelry', 'Silver', 120, 3),
('Steel Watch', 'Accessories', 'Stainless Steel', 90, 12),
('Leather Backpack', 'Bags', 'Leather', 300, 4),
('Suede Shoes', 'Footwear', 'Suede', 150, 8),
('Silver Earrings', 'Jewelry', 'Silver', 60, 18),
('Gold Bracelet', 'Jewelry', 'Gold', 200, 6),
('Canvas Tote Bag', 'Bags', 'Canvas', 50, 15),
('Diamond Necklace', 'Jewelry', 'Gold', 800, 1),
('Stainless Steel Ring', 'Jewelry', 'Stainless Steel', 90, 4),
('Leather Gloves', 'Accessories', 'Leather', 40, 20),
('Gold Earrings', 'Jewelry', 'Gold', 350, 3),
('Silver Watch', 'Accessories', 'Silver', 150, 6),
('Leather Clutch', 'Bags', 'Leather', 120, 9),
('Wool Hat', 'Accessories', 'Wool', 30, 25),
('Gemstone Ring', 'Jewelry', 'Silver', 180, 7),
('Silver Bracelet', 'Jewelry', 'Silver', 70, 13),
('Leather Keychain', 'Accessories', 'Leather', 20, 30),
('Gold Chain', 'Jewelry', 'Gold', 300, 5),
('Silver Earrings', 'Jewelry', 'Silver', 60, 12),
('Steel Watch', 'Accessories', 'Stainless Steel', 90, 10),
('Leather Duffle Bag', 'Bags', 'Leather', 250, 2),
('Cashmere Scarf', 'Clothing', 'Cashmere', 80, 15),
('Gold Ring', 'Jewelry', 'Gold', 180, 4);